# Generated by Django 5.1.3 on 2024-12-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.IntegerField()),
                ('period', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GastoComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('periodo', models.CharField(max_length=50)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
