# Generated by Django 5.1.3 on 2024-12-03 20:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paga', '0002_gasto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='pagado',
        ),
        migrations.AddField(
            model_name='gasto',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
