# Generated by Django 5.1.3 on 2024-12-03 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paga', '0003_remove_gasto_pagado_gasto_fecha_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoComún',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
    ]
